name: Packer AMI Automation (GitHub Actions)

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "latest" 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  packer-build:
    name: Run Packer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Run `packer build`
        id: build
        run: "packer build ."

      - name: List Files
        run: ls -la

  terraform-run:
    name: Run terraform
    needs: [packer-build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: 'terraform init'
        run: terraform init

      - name: 'terraform format'
        run: terraform fmt -recursive

      - name: 'terraform plan' 
        run: terraform plan

      - name: 'terraform apply'
        run: terraform destroy --auto-approve

      - name: List Files
        run: ls -l
        

  s3-upload:
    name: Upload manifest to S3
    needs: [terraform-run]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Check if manifest exists
        run: |
          if [ ! -f ./packer-manifest.json ]; then
            echo "packer-manifest.json not found!"
            exit 1
          fi

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './packer-manifest.json'
  